interface BreedPicturesState {
    [state: string]: any
}

const BreedPictures: BreedPicturesState = {
    'Afghan Hound': require('@assets/BreedProfilePictures/AfghanHound.jpg'),
    'African Hunting Dog': require('@assets/BreedProfilePictures/AfricanHuntingDog.jpg'),
    'Airedale': require('@assets/BreedProfilePictures/Airedale.jpg'),
    'American Staffordshire Terrier': require('@assets/BreedProfilePictures/AmericanStaffordshireTerrier.jpg'),
    'Appenzeller': require('@assets/BreedProfilePictures/Appenzeller.jpg'),
    'Australian Shepherd': require('@assets/BreedProfilePictures/AustralianShepherd.jpg'),
    'Australian Terrier': require('@assets/BreedProfilePictures/AustralianTerrier.jpg'),
    'Bedlington Terrier': require('@assets/BreedProfilePictures/BedlingtonTerrier.jpg'),
    'Bernese Mountain Dog': require('@assets/BreedProfilePictures/BerneseMountainDog.jpg'),
    'Bichon Frise': require('@assets/BreedProfilePictures/BichonFrise.jpeg'),
    'Black Sable': require('@assets/BreedProfilePictures/BlackSable.jpg'),
    'Blenheim Spaniel': require('@assets/BreedProfilePictures/BlenheimSpaniel.jpg'),
    'Border Collie': require('@assets/BreedProfilePictures/BorderCollie.jpg'),
    'Border Terrier': require('@assets/BreedProfilePictures/BorderTerrier.jpg'),
    'Boston Bull': require('@assets/BreedProfilePictures/BostonBull.jpg'),
    'Bouvier des Flandres': require('@assets/BreedProfilePictures/BouvierDesFlandres.jpg'),
    'Brabancon Griffo': require('@assets/BreedProfilePictures/BrabanconGriffo.jpg'),
    'Brittany Spaniel': require('@assets/BreedProfilePictures/BrittanySpaniel.jpg'),
    'Cane Carso': require('@assets/BreedProfilePictures/CaneCarso.jpg'),
    'Cardigan': require('@assets/BreedProfilePictures/Cardigan.jpeg'),
    'Chesapeake Bay Retriever': require('@assets/BreedProfilePictures/ChesapeakeBayRetriever.jpg'),
    'Chihuahua': require('@assets/BreedProfilePictures/Chihuahua.jpg'),
    'Chinese Crested Dog': require('@assets/BreedProfilePictures/ChineseCrestedDog.jpg'),
    'Dandie Dinmont': require('@assets/BreedProfilePictures/DandieDinmont.jpg'),
    'Doberman': require('@assets/BreedProfilePictures/Doberman.jpg'),
    'English Foxhound': require('@assets/BreedProfilePictures/EnglishFoxhound.jpg'),
    'English Setter': require('@assets/BreedProfilePictures/EnglishSetter.jpg'),
    'English Springer': require('@assets/BreedProfilePictures/EnglishSpringer.jpg'),
    'EntleBucher': require('@assets/BreedProfilePictures/EntleBucher.jpg'),
    'Eskimo Dog': require('@assets/BreedProfilePictures/EskimoDog.jpg'),
    'Fila Braziliero': require('@assets/BreedProfilePictures/FilaBraziliero.jpg'),
    'French Bulldog': require('@assets/BreedProfilePictures/FrenchBulldog.jpg'),
    'German Shepherd': require('@assets/BreedProfilePictures/GermanShepherd.jpg'),
    'German Short Haired Pointer': require('@assets/BreedProfilePictures/GermanShortHairedPointer.jpg'),
    'Gordon Setter': require('@assets/BreedProfilePictures/GordonSetter.jpg'),
    'Great Dane': require('@assets/BreedProfilePictures/GreatDane.jpg'),
    'Great Pyrenees': require('@assets/BreedProfilePictures/GreatPyrenees.jpg'),
    'Greater Swiss Mountain Dog': require('@assets/BreedProfilePictures/GreaterSwissMountainDog.jpg'),
    'Ibizan Hound': require('@assets/BreedProfilePictures/IbizanHound.jpg'),
    'Irish Setter': require('@assets/BreedProfilePictures/IrishSetter.jpg'),
    'Irish Terrier': require('@assets/BreedProfilePictures/IrishTerrier.jpg'),
    'Irish Water Spaniel': require('@assets/BreedProfilePictures/IrishWaterSpaniel.jpg'),
    'Irish Wolfhound': require('@assets/BreedProfilePictures/IrishWolfhound.jpg'),
    'Italian Greyhound': require('@assets/BreedProfilePictures/ItalianGreyhound.jpg'),
    'Japanese Spitzes': require('@assets/BreedProfilePictures/JapaneseSpitzes.jpeg'),
    'Japanese Spaniel': require('@assets/BreedProfilePictures/JapaneseSpaniel.jpg'),
    'Kerry Blue Terrier': require('@assets/BreedProfilePictures/KerryBlueTerrier.jpg'),
    'Labrador Retriever': require('@assets/BreedProfilePictures/LabradorRetriever.jpeg'),
    'Lakeland Terrier': require('@assets/BreedProfilePictures/LakelandTerrier.jpg'),
    'Leonberg': require('@assets/BreedProfilePictures/Leonberg.jpg'),
    'Lhasa': require('@assets/BreedProfilePictures/Lhasa.jpg'),
    'Maltese Dog': require('@assets/BreedProfilePictures/MalteseDog.jpg'),
    'Mexican Hairless': require('@assets/BreedProfilePictures/MexicanHairless.jpg'),
    'Newfoundland': require('@assets/BreedProfilePictures/Newfoundland.jpg'),
    'Norfolk Terrier': require('@assets/BreedProfilePictures/NorfolkTerrier.jpg'),
    'Norwegian Elkhound': require('@assets/BreedProfilePictures/NorwegianElkhound.jpg'),
    'Norwich Terrier': require('@assets/BreedProfilePictures/NorwichTerrier.jpg'),
    'Old English Sheepdog': require('@assets/BreedProfilePictures/OldEnglishSheepdog.jpg'),
    'Pekinese': require('@assets/BreedProfilePictures/Pekinese.jpeg'),
    'Pembroke': require('@assets/BreedProfilePictures/Pembroke.jpg'),
    'Pomeranian': require('@assets/BreedProfilePictures/Pomeranian.jpeg'),
    'Rhodesian Ridgeback': require('@assets/BreedProfilePictures/RhodesianRidgeback.jpg'),
    'Rottweiler': require('@assets/BreedProfilePictures/Rottweiler.jpg'),
    'Saint Bernard': require('@assets/BreedProfilePictures/SaintBernard.jpg'),
    'Saluki': require('@assets/BreedProfilePictures/Saluki.jpg'),
    'Samoyed': require('@assets/BreedProfilePictures/Samoyed.jpeg'),
    'Scotch Terrier': require('@assets/BreedProfilePictures/ScotchTerrier.jpg'),
    'Scottish Deerhound': require('@assets/BreedProfilePictures/ScottishDeerhound.jpg'),
    'Sealyham Terrier': require('@assets/BreedProfilePictures/SealyhamTerrier.jpg'),
    'Shetland Sheepdog': require('@assets/BreedProfilePictures/ShetlandSheepdog.jpg'),
    'Shiba Dog': require('@assets/BreedProfilePictures/ShibaDog.jpeg'),
    'Shih Tzu': require('@assets/BreedProfilePictures/ShihTzu.jpeg'),
    'Siberian Husky': require('@assets/BreedProfilePictures/SiberianHusky.jpeg'),
    'Staffordshire Bullterrier': require('@assets/BreedProfilePictures/StaffordshireBullterrier.jpg'),
    'Sussex Spaniel': require('@assets/BreedProfilePictures/SussexSpaniel.jpg'),
    'Tibetan Mastiff': require('@assets/BreedProfilePictures/TibetanMastiff.jpg'),
    'Tibetan Terrier': require('@assets/BreedProfilePictures/TibetanTerrier.jpg'),
    'Walker Hound': require('@assets/BreedProfilePictures/WalkerHound.jpg'),
    'Weimaraner': require('@assets/BreedProfilePictures/Weimaraner.jpg'),
    'Welsh Springer Spaniel': require('@assets/BreedProfilePictures/WelshSpringerSpaniel.jpg'),
    'West Highland White Terrier': require('@assets/BreedProfilePictures/WestHighlandWhiteTerrier.jpg'),
    'Yorkshire Terrier': require('@assets/BreedProfilePictures/YorkshireTerrier.jpg'),

    'Affenpinscher': require('@assets/BreedProfilePictures/Affenpinscher.jpg'),
    'Basenji': require('@assets/BreedProfilePictures/Basenji.jpg'),
    'Basset': require('@assets/BreedProfilePictures/Basset.jpg'),
    'Beagle': require('@assets/BreedProfilePictures/Beagle.jpeg'),
    'Black and Tan Coonhound': require('@assets/BreedProfilePictures/BlackAndTanCoonhound.jpg'),
    'Bloodhound': require('@assets/BreedProfilePictures/Bloodhound.jpg'),
    'Bluetick': require('@assets/BreedProfilePictures/Bluetick.jpg'),
    'Borzoi': require('@assets/BreedProfilePictures/Borzoi.jpg'),
    'Boxer': require('@assets/BreedProfilePictures/Boxer.jpg'),
    'Briard': require('@assets/BreedProfilePictures/Briard.jpg'),
    'Bull Mastiff': require('@assets/BreedProfilePictures/BullMastiff.jpg'),
    'Cairn': require('@assets/BreedProfilePictures/Cairn.jpg'),
    'Chinese Rural Dog': require('@assets/BreedProfilePictures/ChineseRuralDog.jpeg'),
    'Chow': require('@assets/BreedProfilePictures/Chow.jpeg'),
    'Clumber': require('@assets/BreedProfilePictures/Clumber.jpg'),
    'Cocker Spaniel': require('@assets/BreedProfilePictures/CockerSpaniel.jpeg'),
    'Collie': require('@assets/BreedProfilePictures/Collie.jpg'),
    'Curly Coated Retriever': require('@assets/BreedProfilePictures/CurlyCoatedRetriever.jpg'),
    'Dhole': require('@assets/BreedProfilePictures/Dhole.jpg'),
    'Dingo': require('@assets/BreedProfilePictures/Dingo.jpg'),
    'Flat Coated Retriever': require('@assets/BreedProfilePictures/FlatCoatedRetriever.jpg'),
    'Giant Schnauzer': require('@assets/BreedProfilePictures/GiantSchnauzer.jpg'),
    'Golden Retriever': require('@assets/BreedProfilePictures/GoldenRetriever.jpeg'),
    'Groenendael': require('@assets/BreedProfilePictures/Groenendael.jpg'),
    'Keeshond': require('@assets/BreedProfilePictures/Keeshond.jpg'),
    'Kelpie': require('@assets/BreedProfilePictures/Kelpie.jpg'),
    'Komondor': require('@assets/BreedProfilePictures/Komondor.jpg'),
    'Kuvasz': require('@assets/BreedProfilePictures/Kuvasz.jpg'),
    'Malamute': require('@assets/BreedProfilePictures/Malamute.jpeg'),
    'Malinois': require('@assets/BreedProfilePictures/Malinois.jpg'),
    'Miniature Pinscher': require('@assets/BreedProfilePictures/MiniaturePinscher.jpeg'),
    'Miniature Poodle': require('@assets/BreedProfilePictures/MiniaturePoodle.jpg'),
    'Miniature Schnauzer': require('@assets/BreedProfilePictures/MiniatureSchnauzer.jpeg'),
    'Otterhound': require('@assets/BreedProfilePictures/Otterhound.jpg'),
    'Papillon': require('@assets/BreedProfilePictures/Papillon.jpeg'),
    'Pug': require('@assets/BreedProfilePictures/Pug.jpeg'),
    'Redbone': require('@assets/BreedProfilePictures/Redbone.jpg'),
    'Schipperke': require('@assets/BreedProfilePictures/Schipperke.jpg'),
    'Silky Terrier': require('@assets/BreedProfilePictures/SilkyTerrier.jpg'),
    'Soft Coated Wheaten Terrier': require('@assets/BreedProfilePictures/SoftCoatedWheatenTerrier.jpg'),
    'Standard Poodle': require('@assets/BreedProfilePictures/StandardPoodle.jpeg'),
    'Standard Schnauzer': require('@assets/BreedProfilePictures/StandardSchnauzer.jpg'),
    'Teddy': require('@assets/BreedProfilePictures/Teddy.jpeg'),
    'Toy Poodle': require('@assets/BreedProfilePictures/ToyPoodle.jpeg'),
    'Toy Terrier': require('@assets/BreedProfilePictures/ToyTerrier.jpg'),
    'Vizsla': require('@assets/BreedProfilePictures/Vizsla.jpg'),
    'Whippet': require('@assets/BreedProfilePictures/Whippet.jpg'),
    'Wire Haired Fox Terrier': require('@assets/BreedProfilePictures/WireHairedFoxTerrier.jpg'),
}

export { BreedPictures };